#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'alt_vip_vfr_1', class 'alt_vip_vfr'
 * The macros are prefixed with 'ALT_VIP_VFR_1_'.
 * The prefix is the slave descriptor.
 */
#define ALT_VIP_VFR_1_COMPONENT_TYPE alt_vip_vfr
#define ALT_VIP_VFR_1_COMPONENT_NAME alt_vip_vfr_1
#define ALT_VIP_VFR_1_BASE 0x0
#define ALT_VIP_VFR_1_SPAN 128
#define ALT_VIP_VFR_1_END 0x7f

/*
 * Macros for device 'oc_i2c_0', class 'oc_i2c'
 * The macros are prefixed with 'OC_I2C_0_'.
 * The prefix is the slave descriptor.
 */
#define OC_I2C_0_COMPONENT_TYPE oc_i2c
#define OC_I2C_0_COMPONENT_NAME oc_i2c_0
#define OC_I2C_0_BASE 0xa0
#define OC_I2C_0_SPAN 32
#define OC_I2C_0_END 0xbf

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1526321986

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 0
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_0_H_ */
